function makepov(data)

  DataFormat = questdlg('What is the data format?', ...
                         'Data Format', ...
                         'XYZ Columns','A Volume','XYZ Columns');
   
switch DataFormat,
        case 'XYZ Columns',
   PlotFormat = questdlg('Plot Points As...?', ...
                         'Plot Format', ...
                         'Spheres','Cylinders','User Defined PointObject');

case 'A Volume',
  PlotFormat = questdlg('Plot Volume As...?', ...
                         'Plot Format', ...
                         'Cubes','Density Map','User Defined VolumeObject');
end


[f, p] = uiputfile('*', 'POV Filename?:');
cd(p)
fid = fopen([p f], 'w');

fprintf(fid, '%s\n', '// Persistence of Vision Ray Tracer SceneDescription File');
fprintf(fid, '%s\n', '// Generated by makepov.m - Matt Jones,2001');
fprintf(fid, '%s\n', '#version 3.1;');
fprintf(fid, '%s\n', '#include "colors.inc"');
fprintf(fid, '%s\n', 'global_settings{assumed_gamma 1.0}');
fprintf(fid, '%s\n\n', 'camera{ location <50, 50, -50> direction1.5*z right 4/3*x look_at <0.0, 0.0, 0.0>}');
fprintf(fid, '%s\n', 'sky_sphere{ pigment { gradient y color_map{[0.0 color blue 0.6] [1.0 color rgb 1]} } }');
fprintf(fid, '%s\n\n', 'light_source{ 0*x color red 1.0 green 1.0blue 1.0 translate <-30, 30, -30> }');

nsteps = size(data, 1);
spheresize = 1;

switch PlotFormat
case 'Spheres',
for n = 1:nsteps
colstr = ['<'num2str(rand) ',' num2str(rand) ',' num2str(rand),'>'];
outstr = [ 'sphere{ <', num2str(data(n,1)), ',',num2str(data(n,2)), ',', num2str(data(n,3)), '> ' num2str(spheresize)' pigment{color rgb ' colstr '} finish{specular 0.5 phong 0.5} }'];
fprintf(fid, '%s \n', outstr);
if mod(n,100) == 0; disp([num2str(n) ' ' outstr]), end
end
end

fclose(fid);

disp('Done.') 